project:
  type: website
  output-dir: docs

website:
  title: "objectclosure"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/objectclosure
      - icon: twitter
        href: https://twitter.com/objectclosure
format:
  html:
    theme: sandstone
    fontsize: 1.5em
    css: styles.css



