project:
  type: website

website:
  title: "objectclosure"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/objectclosure
      - icon: twitter
        href: https://twitter.com/objectclosure
format:
  html:
    theme: sketchy
    css: styles.css



